package manager

import "errors"

// ошибки
var (
	Err404                               = errors.New("страница не найдена")
	ErrAccessDined                       = errors.New("доступ закрыт")
	ErrConfigPath                        = errors.New("ошибка в пути конфига")
	ErrDescIsEmpty                       = errors.New("поле «Описание объявления» обязательно")
	ErrEmailNotConfirmed                 = errors.New("е-мэйл не подтверждён")
	ErrEmailNotCorrect                   = errors.New("е-мэйл не корректен")
	ErrEmailNotSend                      = errors.New("е-мэйл не отправлен")
	ErrEmptyListCatIDs                   = errors.New("пустой список id категорий")
	ErrFileNotFound                      = errors.New("файл не найден")
	ErrFileSizeIsZero                    = errors.New("файл не имеет размера")
	ErrHashIsNotCorrect                  = errors.New("хеш не корректен")
	ErrInterInYourProfile                = errors.New("войдите в свой профиль, используя ранее введенные данные")
	ErrNotAllowedImageType               = errors.New("не разрешенный тип изображения")
	ErrNotCorrectCat                     = errors.New("указана неверная категория")
	ErrNotCorrectClaimsAndSig            = errors.New("не корректна полезная инф-ия и подпись")
	ErrNotCorrectLoginPassword           = errors.New("не корректные данные - логин или пароль")
	ErrNotCorrectUserID                  = errors.New("не корректен id пользователя")
	ErrNotCreateNewAd                    = errors.New("не создалось объявление")
	ErrNotCreateNewAdDetail              = errors.New("не создались детали объявления")
	ErrNotCreateNewCat                   = errors.New("не создалась категория")
	ErrNotCreateNewCatProp               = errors.New("не создалось свойство категории")
	ErrNotCreateNewImage                 = errors.New("не создалось изображение")
	ErrNotCreateNewPhone                 = errors.New("не создался номер телефона")
	ErrNotCreateNewRecovery              = errors.New("не создалось запись восстановления пароля")
	ErrNotCreateNewSession               = errors.New("не создалась сессия")
	ErrNotCreateNewUser                  = errors.New("не создался пользователь")
	ErrNotFoundAd                        = errors.New("объявление не найдено")
	ErrNotFoundCookie                    = errors.New("не найдена куки")
	ErrNotFoundExternalFilePath          = errors.New("отсутствует внешняя ссылка на файл")
	ErrNotMatched                        = errors.New("отсутствует совпадение")
	ErrNotVerify                         = errors.New("верефикация не верна")
	ErrOnNewRecordNew                    = errors.New("ошибка в проверке новой записи")
	ErrPasswordIsShort                   = errors.New("пароль слишком короткий")
	ErrPasswordsAreNotEqual              = errors.New("пароли не равны")
	ErrPasswordsAreNotEqualCurrentAndOld = errors.New("пароли не равны (новый и текущий)")
	ErrPhoneAlreadyVerified              = errors.New("номер телефона уже верифицирован")
	ErrPhoneCodeIsNotActual              = errors.New("проверочный код уже не актуален")
	ErrPhoneNotCorrect                   = errors.New("не корректный формат номера телефона")
	ErrPhoneNotCorrectCode               = errors.New("код не верен")
	ErrPhoneNotFound                     = errors.New("отсутствует номер телефона")
	ErrPhoneSetNotCorrectNumber          = errors.New("установлен не верный номер телефона")
	ErrPhoneTimeLimit                    = errors.New("пока нельзя отправить смс, подождите неск-ко секунд")
	ErrQueryStringIsShort                = errors.New("строка запроса слишком короткая")
	ErrSessionIsOver                     = errors.New("сессия окончена")
	ErrSMSMoneyInBalanceIsSmall          = errors.New("недостаточно денег на балансе")
	ErrSMSSendingIsNotYetPossible        = errors.New("отправка смс пока не возможна")
	ErrSocAuthUnknown                    = errors.New("не известная ошибка авторизации через соц. сеть")
	ErrTitleIsEmpty                      = errors.New("заголовок пустой")
	ErrTitleIsRequire                    = errors.New("поле «Название объявления» обязательно")
	ErrUndefinedUserID                   = errors.New("не найден id пользователя")
	ErrUndefinedUserRole                 = errors.New("не найдена роль пользователя")
	ErrUserAlreadyExists                 = errors.New("пользователь уже присудствует в системе")
)
